### ISSUE TITLE
Items to Review for the Node.js Collection

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#10]
Howdy folks! We've had a few submissions into the project that I want to bring to your attention. Some for review and some to vote on.

**Items to review:** 

- Benjamin Zaslavsky wrote a blog round creating and submitting an App with Google Home. I gave it an initial review, but am looking for a technical editor to provide their thoughts on it. You can view it in this google document: https://docs.google.com/document/d/1ETI5WerSdRmunWJ_wgfmSE7TyZRwiLcJVej23l8yoUo/edit#heading=h.mnhvjkq7wpr1 cc:@svincent @kinsomicrote

**Items to confirm submission**
- Additionally, Thomas Y wrote a series on http/2: https://medium.com/@ty0h. There's some editorial work that needs to be done, but I wanted to see if folks liked the blogs and would like to see them come into Node.js Collection. If you agree, please leave give it a 🎉 by next Wednesday (November 15). If you don't agree with adding it, please provide a comment on the "why."

- IBM submitted this back in September: https://developer.ibm.com/node/2017/08/31/use-eslint-project/ I think it looks good, but again want to get group consensus here. If you agree that it should be added, please leave a 💜by next Wednesday (November 15). If you don't agree with adding it, please provide a comment on the "why."

- I ran across this post and thought it was really cool: https://medium.com/@peterxjang/modern-javascript-explained-for-dinosaurs-f695e9747b70 It's essentially a history of JavaScript with dinosaurs to tell the story. If you agree that it should be added, please leave a 👍by next Wednesday (November 15). If you don't agree with adding it, please provide a comment on the "why."

**Comment by Tiriel** [comment]
For obvious reasons, I won't say a word on the Google Home App article.
Except that I'll gladly accept any kind of advice!

**Comment by ZibbyKeaton** [comment]
@svincent @kinsomicrote were you able to take a look at the Google Home article? I would ideally like to post it on 11/29. Do you think you can review it by that time and ensure that Ben is happy with your edits? Please let me know asap.

As for the other articles, it seems like folks are good with them. I have a few additional blogs in the hopper (i.e. blog queue) for the "How I Got Into Node" series. 

I would recommend the following publishing dates for the others - ping me if you disagree:
- IBM:  https://developer.ibm.com/node/2017/08/31/use-eslint-project/ 11/22

- Google Home App - 11/29

- JavaScript for Dinos - 12/6

- Thomas Y - 12/13

If you do see anything on Medium that you think would be good for this collection, please share with this group! I think there's a lot of great content already out there that we can add to the collection :)

**Comment by dotproto** [comment]
@ZibbyKeaton, sorry for the delay: I was at a conference when you pinged and it slipped off my radar by the time I got home.

I'll read through Ben's article tonight & add comments to the article as appropriate. I'm not sure if I'll have time to do the other articles tonight, but I've got a lot of time off around Thanksgiving so I should be able to look at the others soon.

**Comment by ZibbyKeaton** [comment]
@svincent were you able to take a look at this over the holiday weekend?

**Comment by dotproto** [comment]
@zibbykeaton sorry, no: something came up and threw me off schedule. I'll review this on tomorrow (Wednesday). Apologies for the delay.

**Comment by ZibbyKeaton** [comment]
No worries. As always, I really appreciate your help and expertise @svincent.

Also as a FYI, Sam's article was published and JavaScript for Dinosaurs accepted our request to add the story to Node.js Collection :)

**Comment by mhdawson** [comment]
One more suggestion: https://developer.ibm.com/node/2017/12/04/node-js-community-code-coverage-a-year-in-review/

**Comment by ZibbyKeaton** [comment]
All - I think at this point we should post Benjamin's blog. It is really straight forward and we've been sitting on it for almost a month. Do others feel the same way? Please send me a 👍if you agree or a 👎if you disagree by this Friday.

**Comment by Tiriel** [comment]
I don't know how you operate usually, but as far as I'm concerned, if any one of you wants to read and make suggestions on the technical side, I'd gladly discuss them and make changes if needed! Otherwise, I evidently won't say I don't want this article to be posted. Just trying to be sure it's up to the usual standards.
@ZibbyKeaton would that be ok for you?

**Comment by ZibbyKeaton** [comment]
We usually have someone give it a quick technical view, but it's just been a bit of time here and I would love to post this. I wanted to open the question up to other technical reviewers to see what they think about this, even it's a quick read that would be great. In the meantime, we created this new item on the Node.js Foundation website where we'll feature what folks are building with Node.js - it's called an application showcase (it's really new and we don't have any submissions as of yet). It's very straight forward. Maybe you want to also post your work here: https://docs.google.com/forms/d/e/1FAIpQLSecCh0Ze8TSjb2d1e8Xooik1Y4Jl4oMkpDxSBVhWYj824Qy5w/viewform @Tiriel

**Comment by Tiriel** [comment]
@ZibbyKeaton thanks a lot! I checked the submission form, but I have pretty much the same problem I had with the original post: I can't name the client or give its logo without permission, which I probably won't be able to get. And it's online but it doesn't have a public repo nor any url (since it's an IoT project). Can it still be posted then?

**Comment by Tiriel** [comment]
@ZibbyKeaton Any update then?

**Comment by ZibbyKeaton** [comment]
@Tiriel opened a new issue on this https://github.com/nodejs/nodejs-collection/issues/13. Planning to post on January 3. I want to post it after the holiday season given that a lot of folks are fairly checked out at this time 😀

**Comment by Tiriel** [comment]
Just saw that, sorry for tagging you in here!
