### ISSUE TITLE
Okay to post How I Got Into #Node in Node.js Collection?

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#11]
Howdy all - Myles Borins thought it would be great to do a series on how folks got into contributing to Node.js. The intention is to provide more context into the folks that makeup the community and why folks like to participate. Hopefully this will inspire folks to begin to contribute to the project.

We've posted four thus far:

- Tierney: https://medium.com/@nodejs/how-i-got-into-node-tierney-cyren-ebf8dd42197a
- Rachel White: https://medium.com/@nodejs/how-i-got-into-node-rachel-white-913671778acc
- Matteo: https://medium.com/@nodejs/how-i-got-into-node-matteo-collina-8542d43afcc2
- Myles and Michael Dawson: https://medium.com/@nodejs/introducing-how-i-got-into-node-398391594833

Is this group okay with me adding it to Node.js Collection? I think it works well for this publication, but let me know if you disagree. If you approve please 👍 by Thursday. If you don't think it should be added please provide a 👎by Thursday.

Additionally, I'm looking for more folks to participate in this. Please let me know if you would like to. Also any other GitHub groups, I should make this request to?

**Comment by Tiriel** [comment]
Just out of curiosity, do you need/want particular profiles for the series?

**Comment by ZibbyKeaton** [comment]
@tiriel if you are contributing, we want to hear from you :) That's really it.

**Comment by Tiriel** [comment]
Well, I’m not sure I qualify with such limited contributions, but I’ll advocate for the series 😄

**Comment by hackygolucky** [comment]
+1 !!

**Comment by ghost** [comment]
+1!
