### ISSUE TITLE
Potential Articles for Node.js Collection 12.5.17

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#12]
There have been a few new articles submitted to Node.js Collection. Please let me know if you want to post. They both look good to me:

- Michael Dawson is intersted in submitting his post "Node.js Community Code Coverage – A year in review" - https://developer.ibm.com/node/2017/12/04/node-js-community-code-coverage-a-year-in-review/ - if you agree please give it a 👍 by Friday EOD

- The Node.js TSC is looking to post a blog on the implementation and planning for ESModules - https://docs.google.com/document/d/1uikgL3vlunCACxQ_w6TqibrjpLEEffQiLcUafh0ErlQ/edit?ts=5a26cd69 - if you agree with us posting, please give it a 😀 by Friday EOD

**Comment by bnb** [comment]
@ZibbyKeaton who would byline on the TSC post? Just the @nodejs account?

**Comment by MylesBorins** [comment]
The modules write up should be a joint byline of me and the tsc

**Comment by bnb** [comment]
@MylesBorins so no issue with posting from the Node.js Medium account, though?

**Comment by MylesBorins** [comment]
@bnb the thought was that since this is official communication regarding the stance taken by the TSC it was more appropriate to post via the Node.js medium account

Open to suggestions if people feel it should be posted on my personal account

**Comment by bnb** [comment]
@MylesBorins awesome, thanks! Just wanted to be sure I understood fully - and I totally agree that posting from the official account is the best approach.

**Comment by ZibbyKeaton** [comment]
@mhdawson your article was posted today: https://medium.com/@nodejs/node-js-community-code-coverage-a-year-in-review-86f4f52f79de.

We will post the ESModules blog tomorrow. Closing this issue now :)
