### ISSUE TITLE
Node.js Collections for Review

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#13]
I haven't received any feedback for @tiriel post, so I'm going to do one more grammar review and post it on January 3 (at the beginning of the year). Given the holiday season, I recommend we obstain from posting blogs unless they are timely. Folks are fairly checked out at this time, on vacation, etc.

@Trott submitted the following to NC as well. It looks good to me and if you agree, please provided a 👍 if you disagree, please provide a 👎by January 3: https://medium.com/@Trott/the-web-tooling-benchmark-is-a-big-deal-ae8691874158. If folks agree, then I will plan to post this on January 8.

We've also received another submission that is in need of review. I can take the first stab at editing, unless someone else would like to gist: https://gist.github.com/WaleedAshraf/4106be954bf522cf25bda3b59e2ea8a6.

Thanks all for helping with this project!

**Comment by Tiriel** [comment]
(Sorry for the tag in the previous issue, seems I was too quick)

This seems all fine by me!

**Comment by Trott** [comment]
> We've also received another submission that is in need of review. I can take the first stab at editing, unless someone else would like to gist: https://gist.github.com/WaleedAshraf/4106be954bf522cf25bda3b59e2ea8a6.

Definitely needs a more concise/easy-to-understand/scannable title. Not sure what that would be, but hopefully someone with editor skills/experience can come up with something.

**Comment by WaleedAshraf** [comment]
@Trott Thanks, I Agree.
By giving more time to think about what I have done, I realized that I'm mocking express session for tests, according to my need. So I have updated the title to be more understandable "How to mock express session?"
Thoughts?

**Comment by WaleedAshraf** [comment]
Was anyone able to review https://gist.github.com/WaleedAshraf/4106be954bf522cf25bda3b59e2ea8a6 ?

I have added few updates in wording and text formatting.
cc: @Tiriel @svincent If you guys have time?

**Comment by ZibbyKeaton** [comment]
@WaleedAshraf can you put this into a Google Document? Might be easier for folks to edit that way.

**Comment by WaleedAshraf** [comment]
@ZibbyKeaton done. https://docs.google.com/document/d/1Sqp33WtQL9qjNNgj2JTh5Fk_pA9Mt1A7vv5JUVPohLs/edit?usp=sharing

Also added link in sheet.

**Comment by Tiriel** [comment]
@WaleedAshraf Going to check this ASAP!

**Comment by Trott** [comment]
Last word of title should probably be _sessions_ rather than _session_.

**Comment by Trott** [comment]
(Or it could be _How to mock an express session_ rather than _How to mock express session_.)

**Comment by Trott** [comment]
Any chance someone can run this through an automated tool like Grammarly (or maybe Word or something has one built-in?) to quickly find and fix the little things like:

`one of the most used package` -> `one of the most used packages`

`and than further apply` -> `and then further apply`

`a express app` -> `an express app`

`testcases` -> `test cases`

`in app` -> `in the app` 

`it's value` -> `its value`

**Comment by Trott** [comment]
Content seems :+1:  to me, but I'm not an express or sinon user, so maybe we can try to loop in someone with that kind of expertise. (Or maybe other reviewers here already are?)

**Comment by WaleedAshraf** [comment]
Ran through Grammarly and updated the doc. Also updated the title. 
Thanks Trott 👍

**Comment by ZibbyKeaton** [comment]
@WaleedAshraf I added a few comments and questions to your post.

**Comment by WaleedAshraf** [comment]
@ZibbyKeaton thanks. Fixed the issues and added few replies for you.

**Comment by WaleedAshraf** [comment]
@ZibbyKeaton I totally forgot about this. 
Not sure if there is an update?

**Comment by ZibbyKeaton** [comment]
@WaleedAshraf I need to take a look at it based on the updates you made. I'm sorry it's taken me so long. I got the flu and have been really delayed with things. I have it on my cal to review this week though!

**Comment by WaleedAshraf** [comment]
No problem and get well soon :) 👍

**Comment by ZibbyKeaton** [comment]
@WaleedAshraf please submit your Medium post to Node.js Collection on Wednesday. I've made you a writer :)
