### ISSUE TITLE
Submission idea: Don't loose ourselves

### ISSUE THREAD

**Issue by Tiriel** [nodejs/nodejs-collection#14]
Hi!

I have a new submission idea I'd like to work on, so I'd like to get advices.

The idea is quite simple:
I originally come from the PHP community. While it was considered a "sub language" some years ago, it has acquired its own legitimacy. But in the mean time, some parts of its community has grown to be more elitist, driving people away. So as our community is growing, and Node.js gaining its own letters of patent, I'd like to make a plea not to take the same path.

I do realize this can be tricky to write, as I don't want to get into a "who's the better language community" sparring match, and I certainly don't want the Node.js Collection to endorse that either.

So any advice on the matter is welcomed!
Cheers!

**Comment by mhdawson** [comment]
My suggestion would be to on the importance of being open and accepting for the Node.js community (and the potential risk of that not becoming the case as a language is successful) as opposed to 'bashing' some other group we should be ok.

**Comment by WaleedAshraf** [comment]
I'll close this issue for now. @Tiriel If you need any advice, feel free to open re-open.
