### ISSUE TITLE
Node.js Collection: Submissions

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#15]
All -

- @NickNaso recently submitted an article for NC about his experience on porting bcrypt to N-API. It looks good to me, but could this group give me a 👍 if they would like to include this submission or a 👎if they would not by next week Wednesday, January 17: https://medium.com/@nicknaso/how-i-ported-bcrypt-to-new-n-api-d0b8c9fe6136

- Safia Abdalla has been writing a series on her blog that dives into code in Node modules. I wanted to reach out to her to see if she would be interested in adding this series into Node.js Collection. What do folks think of this idea? Please leave a comment if you think this makes sense. 

As always thanks for your help here.

**Comment by mhdawson** [comment]
I read the last article by Safia and it seemed like a reasonable candidate to me.

**Comment by WaleedAshraf** [comment]
Safia articles are quite interesting. Might be too deep to understand for some people as she goes line by line of code, but she's doing a great job. ✋

**Comment by Tiriel** [comment]
I do like much Safia's articles. Indeed sometimes the explanations are quite short on some lines of code, but they are nonetheless very interesting.

**Comment by ZibbyKeaton** [comment]
Another article to think of adding to the collection: https://medium.com/@muehler.v/node-js-face-recognition-js-simple-and-robust-face-recognition-using-deep-learning-ea5ba8e852. Let me know if you agree with a yes 👍 or no 👎by Wednesday, January 17.

**Comment by Trott** [comment]
💯 on including Safia's series. (Haven't yet read the other stuff, so not saying anything about it here doesn't mean those articles aren't terrific as well.)

**Comment by Trott** [comment]
The `bcrypt` article seems A-OK to me on a quick pass, except that there are some spelling and grammar errors that are quite noticeable and make it a bit jarring to read. (_guarentees_ instead of _guarantees_, _specially_ instead of _especially_, _more fast_ instead of _faster_, _on experiment_ instead of _an experiment_...) 

I'm happy to give it a technical review at some point soon, but can someone do a grammar/spelling clean-up first?

**Comment by Trott** [comment]
Content-wise, I am totally :+1: on the bcrypt article, although it would be good to get an N-API person to review it. Ping @nodejs/n-api

**Comment by Trott** [comment]
Facial-recognition article seems 👍 content-wise too. Like almost everything that gets submitted, it could definitely use some attention from an editor. (There's no shame in needing editorial review, of course. Even full-time professional writers need it. Writing is difficult.) If it helps, the issues in this one tend to be punctuation (missing commas, missing apostrophes, missing hyphenation) and capitalization (notably, _euclidean_ should be _Euclidean_).

**Comment by mhdawson** [comment]
We were discussing this in the n-api meeting today and we are all +1  on the @NickNaso  article (Note he is part of the team :))

**Comment by ZibbyKeaton** [comment]
Thanks for your feedback here @Trott I asked Nicola if I could go into this and edit for grammatical purposes.

**Comment by mhdawson** [comment]
@ZibbyKeaton do you know were we are on the N-API bcrypt article ?

**Comment by ZibbyKeaton** [comment]
It has been posted and I requested some grammatical suggestions @mhdawson

**Comment by mhdawson** [comment]
@ZibbyKeaton thanks for the update.

**Comment by ZibbyKeaton** [comment]
@WaleedAshraf I would like to post your blog on Wednesday. I just added you as a writer to the publication, so please submit it directly on Wednesday. Just go to the bottom of the article with the three dots and it will give you the option to submit it!

**Comment by WaleedAshraf** [comment]
Sure 👍 @ZibbyKeaton 
Thanks.
