### ISSUE TITLE
Seeking Technical Editors for the Node.js Collection 

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#16]
I would love to expand our list of technical editors to the Node.js Collection. We get a lot of abstracts from folks that want to write a piece of content for the Node.js Collection, and technical editors are essential in reviewing these abstracts and providing feedback once the article is written. 

Does anyone have any interest in becoming a technical editor? It's a fairly light lift and you usually won't be reviewing more than one post per month (if that). Let me know if this interests you or if you know someone in the community that likes to write/edit that might be a good fit.

Happy to answer any and all questions.

**Comment by Tiriel** [comment]
Hey!
I'd love to help actually, but as I consider myself pretty much of a low level js dev for now, I don't know if I'm fit.

On the other hand, it could be seen as noob-reading the articles to ensure the can be understood by anyone... :smile:

**Comment by dotproto** [comment]
@ZibbyKeaton, apologies for not being more involved; I want to try to change that. My biggest stumbling block to contributing right now is that I lost the Google Doc link for articles waiting for review. Are we still using a Google Doc to track that or is there another system?

**Comment by ZibbyKeaton** [comment]
@svincent I've been adding articles to the Google Doc here: https://docs.google.com/spreadsheets/d/1xT8KEolYqcKj2L4Dijx8dbvwqKsOL_2uCADhK_xzOx8/edit#gid=0 and also trying to post them on GitHub. We only have one in the hopper right now that needs to be reviewed if you do have the time. I'll try to do a better job at refreshing this and then pinging people about it. 

@Tiriel we would love your help. If we have blogs focused for new devs that could be perfect for you to help edit.

**Comment by WaleedAshraf** [comment]
I can spare some time. Not a pro dev but can do basic technical reviews. 👍

**Comment by WaleedAshraf** [comment]
I have added few comments for "How locize leverages serverless" post in google doc.
It seems fine to me from technical point. Added few comments where I think it can be improved.
