### ISSUE TITLE
Smashing Magazine Seeking Contributed Articles on Performance

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#17]
This topic is outside of the Node.js Collection, but relates to developers that like to write, so I figured this would be the best place to share!

I was recently talking with a contributor to Smashing Magazine (thank you for the intro @bnb ). They are currently focusing on articles related to performance leading up to an event that they are hosing February 7 - 8: https://www.smashingmagazine.com/events/london-2018/. This could be a new project or a new tech that might help performance - please send me topics related to Node.js, JavaScript and the larger ecosystem. A few topics that initially came to my mind were TurboFan, HTTP/2, debuggng... It would need to be high-level and discuss how X impacts web development. 

If you have any topics that come to mind here, send them my way in abstract form (zkeaton@linuxfoundation.org), i.e. what would the title of the piece be; what is the name of the tech and how does it improve performance and impact web developers; why should people be paying attention to it.

I know this is not super specific, but they are generally looking for a wide range of topics, the general theme just needs to be performance and it needs to be relatable to web dev.  

Cc: @fhinkel here in case V8 team has some thoughts.  

Also, feel free to share this 😀

**Comment by hashseed** [comment]
I would be willing to contribute something related to V8's startup snapshots and code caching. But I have no idea what the target audience is and what level of expertise I can expect.

**Comment by ZibbyKeaton** [comment]
@hashseed audience is web developers (anything from web designers, Go developers, Node.js developers, JavaScript developers). The magazine hits a large audience, so it shouldn't be too technical. You want your content to relate to 10,000 software developers who are concerned about how big changes in the pipeline will impact them.

**Comment by bmeurer** [comment]
I could write something about TurboFan I guess. What's the timeframe? Does it need to be published before Feb 7th?

**Comment by ZibbyKeaton** [comment]
@bmeurer yes, it would need to be published before Feb 7th. If you don't have the time, they are consistently looking for articles that would interest a web dev audience, so if anything comes up like a new feature with V8, strategy, etc. It might be worth submitting something to them.

**Comment by bmeurer** [comment]
@ZibbyKeaton I talked to @mathiasbynens about this yesterday, and we'd love to contribute an article about new optimizations in TurboFan, but we can't make the deadline, since we're both on conferences/TC39 in the next weeks, and there's obviously other work. We could however do an article later this year.

**Comment by ZibbyKeaton** [comment]
@bmeurer that's totally fine. Let me know when you have the time to write something up, and I'll share with the magazine.
