### ISSUE TITLE
Submission: Web Tooling Benchmark, Details

### ISSUE THREAD

**Issue by jasnell** [nodejs/nodejs-collection#18]
A more detailed post about the web tooling benchmarks

https://medium.com/@jasnell/node-js-and-the-web-tooling-benchmark-c982a88cf5b6

**Comment by ZibbyKeaton** [comment]
Does this group have any edits to this. Please provide any comments that you see fit and provide a 👍 by next Thursday, January 25.

**Comment by ZibbyKeaton** [comment]
@jasnell didn't hear anything back ground this group. Are you okay with me posting this on N.C. on Monday, February 12?

**Comment by jasnell** [comment]
Yep of course!

**Comment by ZibbyKeaton** [comment]
@jasnell Medium updated it's policy and publications can no longer add stories to their publication. What you have to do now, is invite someone to be a writer and then the writer needs to submit his/her story to the publication. I just added you as a writer to the publication, so you should now be able to submit this story to the Node.js Collection. At the bottom of the story, hover over the three dots and you should have the option to add to a publication.

**Comment by ZibbyKeaton** [comment]
Hey @jasnell did you submit your story? I haven't seen it come through yet...
