### ISSUE TITLE
Request: Planning for Apostrophe 3.0

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#20]
Submission: The ApostropheCMS team has been hard at work improving our software and we’ve started the planning for Apostrophe 3.0. In our latest Medium post we talk about how we are going to switch to a front-end framework like React or Vue.js for the admin, how we plan to update the asset pipeline to include a modern preprocessor out of the box, and how we are reaching out to the community for feedback to help inform our choices.

The link:  https://medium.com/@apostrophecms/planning-for-apostrophe-3-0-5b20558874de

Please let me know if folks agree with adding this by providing a 👍. If you do not want to add it, please provide a 👎 with reasons why. Comments on how this can be improved are much appreicated by this group. Feedback needed by February 20, 2018.

**Comment by Trott** [comment]
No opinion on the content. The article itself is refreshingly light on typographical errors compared to other entries we've had. There is a typo in the very first sentence (missing the word *a* between *over* and *year*). First impressions matter, so I would definitely get that fixed before publishing.

**Comment by Trott** [comment]
(While at it, the first sentence should also get a comma after *ago*, and it should be styled *npm* rather than *NPM*. I mean, might as well get all the little fixes in that first sentence. :-D )

**Comment by bobclewell** [comment]
@Trott, thanks for the feedback. I made the edits you noted.

**Comment by ZibbyKeaton** [comment]
Few other suggested grammatical changes: 

- Consistency in writing Vue as Vue.js and React as React.js (just keep the writing of these two consistent throughout)

- Suggest writing front-end as frontend, and again keep consistent through entire piece

- Define splash? Any quantitative data you can share on download numbers?

- A recurring theme being the front-end architecture of the admin experience and the amount of dependencies Apostrophe was pushing to the browser, much of the time unnecessarily. **This sentence doesn't make sense. Sounds like this is what is promoting the entire piece. I would explain it a little** more. Example: One of the biggest points of feedback was around XXX. We heard you and are working to make the change in Apostrophe 3.0. The blog explains X, Y and Z

- Take out the "And" in the "And we also plan to marry that framework." Sentence should read: We plan to marry *this* framework to our current framework. This allows most admin UI continues to be provide automatically with no need for boilerplate code generations. 

- Take out intentional: Last year we worked with experienced designers to facilitate targeted testing with...

- New paragraph: Most of these improvements...

- Take out "will" and "And". Change sentence to read: This leads to better standardization and compartmentalization of Apostrophe's components to create a more resilient frontend. 

- Change sentence to: Apostrophe’s current built-in asset pipeline will be replaced with an implementation that integrates a widely used tool (add comma) such as Webpack or Gulp,

- Take out "a more modern" ... for asset builds that includes a modern CSS prepocessor...

- Take  out "And": You will have the option of using it for your project-level assets as well.

- Take out "still and simply"" we currently push too much stuff (add out) to the public.

- Take out eclipse and "and": This option is likely to appear even before 3.0 arrives.

- Change comma to em dash: - like modals, editors (take out comma) and in-context admin chrome.

- Add comma: As we continue fleshing out a roadmap for Apostrophe 3.0 (add comma), we'll be...

**Comment by bobclewell** [comment]
@ZibbyKeaton Thanks for all the fantastic feedback! I've addressed everything except (note to self) the below 2 items. I'll likely address those tomorrow after a bit more thought.

* Define splash? Any quantitative data you can share on download numbers?

* A recurring theme being the front-end architecture of the admin experience and the amount of dependencies Apostrophe was pushing to the browser, much of the time unnecessarily. This sentence doesn't make sense. Sounds like this is what is promoting the entire piece. I would explain it a little more. Example: One of the biggest points of feedback was around XXX. We heard you and are working to make the change in Apostrophe 3.0. The blog explains X, Y and Z

**Comment by bobclewell** [comment]
@ZibbyKeaton I've made some additional edits to address your questions by updating the introduction. Again, thanks for the feedback! We are looking forward to its publication in the collection. Cheers.

**Comment by ZibbyKeaton** [comment]
Thanks @bobclewell. Let's plan to get this on the blog on Wednesday of next week. In terms of next steps, I will make you ApostropheCMS a writer of the Node.js Collection and then you can submit the story on Wednesday. There's a new process for publications, so I can no longer request a story. You have to be a writer of the publication and submit it on your own. Sound good to you?

**Comment by bobclewell** [comment]
Sounds good to me @ZibbyKeaton, I think. Just to be clear, on Wednesday, I should resubmit the article to `medium@nodejs.org` after you make our account a writer, correct?

**Comment by ZibbyKeaton** [comment]
That is correct @bobclewell

**Comment by ZibbyKeaton** [comment]
Added ApostropheCMS as a writer - please feel free to submit the article @bobclewell

**Comment by bobclewell** [comment]
@ZibbyKeaton Done. 😄
