### ISSUE TITLE
Node.js Collection Submission February 21, 2018

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#21]
I have two article submissions for Node.js Collection. 

The first one is around the Node.js Security Roadmap (it needs a title). All and all the content looks good to me and I didn't see a ton of grammatical errors. Could folks give me a 👍 if they agree that this should be added to Node.js Collection or a 👎 if you don't think it should be added by February 28.

Node.js Security Roadmap here: https://docs.google.com/document/d/1kXJ7izscnOTR_K75BPXH-1BfPKZ3UN80Z5VipRv2ap4/edit

The second one is titled "Heroku's handshake with mlab." At first glance, this article needs work grammatically and structurally. Before we go through this process, I want to confirm that folks think this content is of interest to Node.js developers. If you agree and want to add it to the collection, please give a 👍. If you don't agree please give a 👎 by February 28. 

Heroku’s handshake with mlab: https://medium.com/@_Obbap/7fea651fa8c2

**Comment by Trott** [comment]
@ZibbyKeaton Following the Google Docs link you provide results in this:

<img width="788" alt="screen shot 2018-02-21 at 2 51 58 pm" src="https://user-images.githubusercontent.com/718899/36510121-d2215ea0-1716-11e8-87b9-6b85f1be9252.png">

I (and other reviewers) could ask permission to see the doc if necessary, but if it could be opened up a bit so that wasn't necessary, that would probably be better.

**Comment by MylesBorins** [comment]
Can you try this link and tell me if it any better?

https://docs.google.com/document/d/1kXJ7izscnOTR_K75BPXH-1BfPKZ3UN80Z5VipRv2ap4/edit?usp=drivesdk

**Comment by Trott** [comment]
@MylesBorins Same result with that link.

**Comment by MylesBorins** [comment]
I'll fix this tomorrow. My apologies

**Comment by ZibbyKeaton** [comment]
This link should work. I only have comments enabled, so we can see the changes. If folks have edits suggestions, please leave a comment. https://docs.google.com/document/d/1LjdipYoCgNtIAdOvBZl7_5Jg91qC1cLtYqtecQpW7L0/edit

**Comment by ZibbyKeaton** [comment]
As a follow up to this, @mhdawson and the TSC have been working on a blog around their initiatives and roadmap for the year. I would like to post this tomorrow. Please let me know if anyone has objections: https://docs.google.com/document/d/1JKXqrgImDg7ZDtumtjHbsdXHO-6_Zt2nlRWmRxbo_40/edit

**Comment by MylesBorins** [comment]
Are we good to post the security roadmap now? I know that @mikesamuel was considering posting to their personal medium... what are the next steps?

**Comment by WaleedAshraf** [comment]
I don't think *Heroku’s handshake with mlab* is related to Node.js OR Node.js developers. It's a nice step by step guide on how to integrate mlab in Heroku but no relation to Node.js at all.


👍 for Node.js Strategic Initiatives and Security Roadmap

**Comment by ZibbyKeaton** [comment]
@MylesBorins @mikesamuel - I have a few super minor items that need to be addressed before we post this: we need a title and an image. I always request an image to be included as this looks better when we share it on social + it helps us with engagement. Once we have this, it should be good to post. I know with other community-related posts, we've generally had the Node.js Foundation post it and provide a bio of the author, however I am more than happy to add Mike as a writer to the Collection and then add the post. We leave this choice up to the writer :)

**Comment by ZibbyKeaton** [comment]
@MylesBorins @mikesamuel updated the document with a suggested title and suggested images. LMK what you think, and please confirm if Mike is going to post to his Medium blog or if you want me to post it on the Node.js Foundation's.
