### ISSUE TITLE
Node.js Collection Submissions March 8

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#22]
I have just one submission for this week:  https://blog.octo.com/en/clean-node-part-1/. Please let me know if folks want to add it into the Node.js Collection publication with a 👍 or not add it in with a 👎 by March 15 (next Thursday). I need to confirm a few things as well with this author, mainly that this publication will allow us to publish it on our collection. I will also request that npm is not capitalized. Any other major glaring issues this group sees with this post?

**Comment by ZibbyKeaton** [comment]
Another article to add to the list here from Matteo Collina and Tomas Della Vedova around Fastify hitting 1.0.0. Please let me know if you want to add it into the Node.js Collection publication with a 👍 or not add it in with a 👎 by March 15.

**Comment by SarahKConway** [comment]
:+1:

**Comment by WaleedAshraf** [comment]
@ZibbyKeaton just to be clear, it's this article: https://medium.com/@fastifyjs/fastify-goes-lts-with-1-0-0-911112c64752

Right?

I saw few typos in it, like:
forwishen -> fruition
`fast-json-stringify` -> code blocks are not working
contributors that assisted us though -> contributors that assisted us **through**
Fastify as part as their daily job -> Fastify as part **of** their daily job

**Comment by ZibbyKeaton** [comment]
Yes @WaleedAshraf! Sorry for not including it the first time around :)
