### ISSUE TITLE
Create a tag for "How I Got Into Node" posts

### ISSUE THREAD

**Issue by trivikr** [nodejs/nodejs-collection#24]
_From @trivikr on March 15, 2018 8:44_

Hi,

I came across "How I Got Into Node" series from nodejs/community-committee/issues/138, the first post can be be viewed [here](https://medium.com/the-node-js-collection/introducing-how-i-got-into-node-398391594833)
There are [more posts](https://www.google.co.in/search?q=%22how+i+got+into+node%22), but I couldn't find a way to view them as a collection/series

If we create a tag for "How I got into Node" posts, it'll be easy to access all of them (example [nodecore](https://medium.com/the-node-js-collection/tagged/nodecore) tag)

Regards,
Trivikram

_Copied from original issue: nodejs/community-committee#278_

**Comment by trivikr** [comment]
_From @bnb on March 15, 2018 13:27_

Hey there @trivikr 👋

This is probably a discussion that best goes into the [Node.js Collection Initiative](https://github.com/nodejs/nodejs-collection) repo, since the Node.js Collection is where that content lives.

**Comment by bnb** [comment]
cc @ZibbyKeaton - this is definitely an interesting idea, though I don't know if there's actually space in the nav for it 😬

**Comment by trivikr** [comment]
Tags improve Medium experience in other ways ([blog post](https://blog.medium.com/introducing-tags-to-medium-1b6182fd3dbd#529c))

Even if there's no space in the nav, viewers will be able to browse the tag at the bottom of the "How I got into Node" posts. That tag is currently not present ([example post](https://medium.com/the-node-js-collection/how-i-got-into-node-uttam-pawar-4c62d3840a78))

**Comment by ZibbyKeaton** [comment]
My general strategy with tags is to make the articles more discoverable and less about navigation. I tag them with Node.js and JavaScript, so Node.js and JavaScript developers might find them. Additionally, I tag them with open source as this then generates these posts into our community tab on the publication page. There are a lot of community posts, however, and thus the series gets drowned out a bit. I created another specialized tag of HowIGotIntoNode. Now when you go to Medium, you can find all the posts for better navigation. Let me know if this is what you were after @trivikr

**Comment by trivikr** [comment]
Thanks @ZibbyKeaton 
I'm able to see "How I got into #Node" posts under HowIGotIntoNode tag at https://medium.com/the-node-js-collection/tagged/HowIGotIntoNode

The tag is visible at the end of the individual posts too ([example post](https://medium.com/the-node-js-collection/how-i-got-into-node-uttam-pawar-4c62d3840a78))
This will help readers to read related posts.
