### ISSUE TITLE
Submission Requests for Week of March 26

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#25]
Howdy all - I've received a few submissions for the Node.js Collection that you can all find in our shared editorial calendar: https://docs.google.com/spreadsheets/d/1xT8KEolYqcKj2L4Dijx8dbvwqKsOL_2uCADhK_xzOx8/edit?usp=drive_web&ouid=107471902318831510062

I need one of our technical editors (or two) to look at these articles and confirm that they are okay to post from a technical standpoint. I will then do a grammar review. 

Going forward, I'm going to request that all of the submissions be converted into google documents as it is a lot easier to edit. Also today, I accidentally thought I was editing a submission in private, but was leaving public notes. To avoid this mistake again, I figure it is best to edit in google documents :)

**Comment by WaleedAshraf** [comment]
I have found few grammar  mistakes in Fiqri Ismail post: https://medium.com/@fiqriismail/writing-your-first-node-js-rest-api-service-5608f2fb703a

But there is no google doc link in the sheet. Same case for other articles.

**Comment by ZibbyKeaton** [comment]
@WaleedAshraf I requested they send a google link, but haven't heard back.

As an update, I went through and edited a few articles this morning. I would like to publish @WaleedAshraf 's post week of April 16. @bnb or @svincent do you have any comments/questions on this post from a technical perspective? https://docs.google.com/document/d/1a3vz2743yKP_fC72BNbVl6vLrW0aF3rflauJ-SuQV1o/edit#heading=h.d0626x9jkhii

There was also a blog submitted on http/2 that's been edited by a few folks from the TSC that I would like to publish on April 11 - I still have a few comments in there: https://docs.google.com/document/d/1LbzeH1UOWO7glqLI0_Z_ZC3q0rCw79G2JVe9WZSkFJQ/edit?usp=sharing

Lastly, I made some edits on Node.js in Africa. It looks good to me, and once we get the suggested adjustments and comments resolved, I would like to publish this the week of April 16 as well cc: @codeekage

There's a few more posts that need editing; I'll try to get to it either today or this weekend. Here's the editorial calendar for reference: https://docs.google.com/spreadsheets/d/1xT8KEolYqcKj2L4Dijx8dbvwqKsOL_2uCADhK_xzOx8/edit#gid=0

**Comment by codeekage** [comment]
thanks, @ZibbyKeaton, and @WaleedAshraf for the edits... However, I'd love if @WaleedAshraf and @ZibbyKeaton would be interested in the writing programme.

**Comment by WaleedAshraf** [comment]
@codeekage thanks and Sorry I didn't understand what you mean by "writing programme"?

**Comment by codeekage** [comment]
From the documentation you review, I'm not so sure if you noticed it, but you could review the document again for the Node.js Africa Writing Programme.

**Comment by WaleedAshraf** [comment]
Oh, I get it.
Well, I'm not a professional blogger or writer. 😭  But still, I would love to provide any assistance/help if needed. 👍

**Comment by ZibbyKeaton** [comment]
@codeekage I can try to help as best as I can. Just let me know when and what you would need. 

I have received the google document for the article "Clean Node." I need to make a few minor edits, but overall the content looks really good. Please let me know if someone on the technical review team sees any red flags by next Thursday (4/19). If you also agree that this should be posted, please provide a 👍 by 4/19. If you disagree and don't think it should be posted, provide a 👎by 4/19.

Article here: https://docs.google.com/document/d/1IWd1gEUU9z7jVrkzgCpsL_Qv11DYhwKlzpkgs4SK1m4/edit

**Comment by mhdawson** [comment]
Not sure if this is still the right place but I'd like to add https://developer.ibm.com/node/2018/04/29/node-js-help-and-support/ for consideration.

**Comment by ZibbyKeaton** [comment]
@mhdawson this looks good. I put it in our editorial calendar. Mind providing me with Gireesh's email address so I can reach out directly on adding this and bio requests?

**Comment by mhdawson** [comment]
@ZibbyKeaton done through email.

**Comment by ZibbyKeaton** [comment]
I think all of these posted, so I'll close this comment now :)
