### ISSUE TITLE
Adding release line news to Node.js Collection

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#26]
I would like to add the recent announcement of Node.js 10 and our updates on what's happening with Node.js versions in April to the Node.js Collection. Here are the blog for reference:

Node.js 10 News: https://medium.com/@nodejs/the-node-js-project-introduces-latest-release-line-node-js-10-x-bf07abfa9076

Node.js April Release Line News: https://medium.com/@nodejs/april-2018-release-updates-from-the-node-js-project-71687e1f7742

Let me know if this group is okay with that by tomorrow. Going forward, I would like to have permission to add these into the Node.js Collection. I think it's important to amplify news going out as it relates to release updates. Do others agree or would you prefer that I submit these before I add to the Node.js Collection?

**Comment by mhdawson** [comment]
+1 from me.
