### ISSUE TITLE
Node.js Collection Submission for May

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#27]
We've received a flurry of submission and I wanted to confirm with this group that you are okay with us posting the below - I would need to do minor grammar scrubs on a few. 

Since there are multiple submissions here, please list out all of the titles with a Y next to the ones that you would like to add and a N next to ones that you do not think are appropriate with a sentence explaining the reason why. Feedback requested for these by May 21.

- [Building your first Serverless app in Node.js with AWS Lambda + S3 + API Gateway ](https://www.google.com/url?hl=en&q=https://docs.google.com/document/d/1FdYBHoARabKv0sHqETiCNFiMNRD3RzSgLrZWiclWtZ8/edit?usp%3Dsharing&source=gmail&ust=1526403994704000&usg=AFQjCNHEX8wA7jrkkprS3NywiaGgb0KsqA)

- [NATIVE EXTENSIONS FOR NODEJS](https://www.nan-labs.com/blog/native-extensions-for-nodejs/)

- [Evaluating Cypress and TestCafe for end to end testing](https://medium.com/yld-engineering-blog/evaluating-cypress-and-testcafe-for-end-to-end-testing-fcd0303d2103)

- [Machine Learning in JavaScript with Propel](https://medium.com/yld-engineering-blog/machine-learning-in-javascript-with-propel-50bfa46e8b03)

- [So, you’re thinking about updating your Hapi.JS server to V17?](https://medium.com/yld-engineering-blog/so-youre-thinking-about-updating-your-hapi-js-server-to-v17-b5732ab5bdb8)

- [Microservices in the microcosm](https://medium.com/yld-engineering-blog/microservices-in-the-microcosm-238752a98655)

- [Bringing the nodejs/help backlog down by 90% over 2 months, and best practice recommendations for raising issues](https://developer.ibm.com/node/2018/04/29/node-js-help-and-support/)

**Comment by mhdawson** [comment]
In respect to this one: NATIVE EXTENSIONS FOR NODEJS I'd like this line

```
At this moment, N-API is under experimental state.
```
updated to reflect the current status (stable in master/10.x, soon to be stable in 8.x and experimental in 6.x)

**Comment by mhdawson** [comment]
I went to look at this one: Machine Learning in JavaScript with Propel and the site just says

```
TensorFlow.js was recently released. It is well engineered, provides an autograd-style interface to backprop, and has committed to supporting Node. This satisfies our requirements. It is counterproductive to pursue a parallel effort. Thus we are abandoning our backprop implementation, TF C binding, and the TF/DL bridge, which made up the foundation of the Propel library. We intend to rebase our work on top of TFJS.

Our high-level goal continues to be a productive workflow for scientific computing in JavaScript. Building on top of TFJS allows us to focus on higher-level functionality.

We have no release at this time.

github.com/propelml/propel
```
So I'm thinking that one may not make sense.

**Comment by WaleedAshraf** [comment]
I was able to go through these.
- NATIVE EXTENSIONS FOR NODEJS **(Y)**
- Evaluating Cypress and TestCafe for end to end testing **(Y)**
- Microservices in the microcosm **(N)** 
It's a good article, but doesn't share anything about Nodejs or even Javascript. I think people who follow Nodejs-Collection, expect something related to Nodejs.
- Bringing the nodejs/help backlog down by 90% over 2 months, and best practice recommendations for raising issues. **(Y)**
- Building your first Serverless app in Node.js with AWS Lambda + S3 + API Gateway. **(Can't comment because it's mine 😄)**

**Comment by ZibbyKeaton** [comment]
@WaleedAshraf article looks good. I provided a few edits to it (track changes on) and had a couple of suggestions and questions, once you address these feel free to submit it to Node.js Collection.

**Comment by WaleedAshraf** [comment]
@zibbykeaton thanks. 
I will submit it within few days.

**Comment by ZibbyKeaton** [comment]
All, I have another submission. This is around running Node.js on different GCP products - it's a series. Can folks let me know if they would like add this in by June 13 (i.e. next Wednesday): https://medium.com/@melnyk.dima/time-to-hello-world-part1-overview-8624fa38e523
