### ISSUE TITLE
N-API Blog Post Looking to Post Tomorrow, 7.18.18

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#28]
Howdy all - The N-API team would like to post a N-API centric blog tomorrow, 7.18.18 as they will be speaking at Node Summit and want to make sure folks are aware of their presentation. I think this looks good, but wanted to make sure others were onboard with this: https://medium.com/@arunesh/b76cfab49bcc

Please give me a 👍 (if you agree with posting) or 👎(if you disagree with posting) by tomorrow 7.18.18 at 10am ET.

ALSO, if you are attending Node Summit and have a talk on the technical aspects of the project Node.js or have a community talk, I encourage you to draft a blog post on it and/or if you want to send info to me, I'm happy to write a recap blog around all the amazing Node.js Project technical and community content that was featured for folks that weren't able to attend.

**Comment by NickNaso** [comment]
I just read the article and seems good to me. I'm part of N-API team so I don't vote. I want only leave a positive feedback about the content of the article.

**Comment by Trott** [comment]
I assume this will get a good round of edits before posting. If nothing else gets edited, at least please correct the typo in the first sentence. (Should be either "You may hear" or "You may have heard" but not "You may heard".) 

Other stuff:

* Missing hyphens ("built in" -> "built-in", "Compute intensive" -> "Compute-intensive", "hands on" -> "hands-on")
* Mixing of different verb tenses ("Porting a module that your app depends on and upstream it" should say "upstreaming") 
* "such that is uses" -> "such that it uses"
* Missing commas ("As features get added to N-API we..." should have a comma between "N-API" and "we". "As of version 8.11.2 all..." should have a comma between "8.11.2" and "all".)
* Misplaced whitespace: "docs :" should be "docs:"

**Comment by Trott** [comment]
Would this be the right place to suggest https://medium.com/@Trott/windows-developers-node-js-core-wants-you-728a6107a1bb for the collection? (EDIT: If it's not aligned with the usual focus of the Node.js Collection, then please spike it.)

**Comment by ZibbyKeaton** [comment]
Thanks @Trott this is the right place to post this and it's perfect for Node.js Collection as it relates to our community. If folks want to add this to the collection, please provide a 👍to this post, if you don't want to add it, please provide a 👎 to this post by next Wednesday, July 25.

**Comment by ZibbyKeaton** [comment]
@Trott is this post still relevant? I realize I never followed up with you on this. You are an author of the Node.js Collection, so you should be able to submit this directly.

**Comment by Trott** [comment]
I consider it still relevant, yes.

**Comment by ZibbyKeaton** [comment]
I am going to close this issue - @Trott please submit to Node.js Collection and let me know if you have any trouble with this.
