### ISSUE TITLE
Blog Posts for Week of August 27

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#29]
All -

I received a few posts for the Node.js Collection this August. It's been fairly quiet for August and July. Both of these look good to me, but I wanted to confirm if the group had any red flags or suggestions. Please send them to me by next Monday, August 27. I'll aim to post one on Tuesday and one on Thursday of next week:

- Image Manipulation Using Express: https://medium.com/@Packt_Pub/image-manipulations-using-express-7398a6fa1491

- Continuous Deployment for Node.js on the Google Cloud Platform: https://medium.freecodecamp.org/continuous-deployment-for-node-js-on-google-cloud-platform-751a035a28d5

**Comment by Trott** [comment]
The code formatting in the image manipulation article makes the code nearly unreadable. (I'm not talking about the first two screenshots, but the many subsequent segments where there's actual code you can copy/paste.) Honestly, I'm not sure it's worth reviewing the article until that's fixed. It will be error-prone to review the code without any indentation like that, etc.

Example of the problematic code formatting:

<img width="510" alt="screen shot 2018-08-21 at 10 56 15 am" src="https://user-images.githubusercontent.com/718899/44419761-e7c10500-a530-11e8-812e-9e9919f62471.png">

**Comment by WaleedAshraf** [comment]
Agree with @Trott 
All code snippets in the first article should be created using gist.

Thumbs up 👍 for the second article: Continuous Deployment for Node.js on the Google Cloud Platform.

**Comment by ZibbyKeaton** [comment]
Thanks for the feedback. I made the request with the author and will share the updated version when I have it. I've received a few more articles from Matheus Marchini who is a member of the Diagnostics Working Group. Below is a full article that he's written and another is an abstract. I like both topics; let me know what y'all think with a 👍 or 👎:

**Taming the dragon: using llnode to debug your Node.js application:** https://medium.com/sthima-insights/taming-the-dragon-using-llnode-to-debug-your-node-js-application-fc54c6efd0f1

**Title: Finding performance bottlenecks in your Node.js application**

Node.js has excellent performance, thanks to V8 and its single-threaded event loop, but sometimes our application can run slow. Finding these performance bottlenecks can be tricky, that's why there are tools created exclusively to help developers find and fix these bottlenecks. V8 offers two tools out of the box: a `--prof` flag and the CpuProfiler (through the Inspector Protocol), but there are other tools supported, such as Linux perf and dtrace. I want to write a summary of these tools so that developers know they exist and can choose the fittest one when necessary.

**Comment by WaleedAshraf** [comment]
**Taming the dragon: using llnode to debug your Node.js application:**
The article is well written, but I think It doesn't solve the problem it looks it is intended for. As I read the whole article and the last line is:
> Unfortunately, llnode can't tell where this array is located yet, but there's an open issue to add this feature in the future.

It should be mentioned explicitly in the start.

**Finding performance bottlenecks in your Node.js application:** 
👍 for abstract.

**Comment by ZibbyKeaton** [comment]
The article from Packt has been updated (this is the one where we had issues with the code block). Let me know if this works or if want the gist links directly into each section that shows code: 
https://medium.com/@Packt_Pub/image-manipulations-using-express-7398a6fa1491

We also have a new submission, "8 Keys to Successful Third Party API Integration." It reads well to me and although not directly related to the Node.js topic, I think Node.js developers will find it helpful. Let me know what folks think by next Tuesday (September 4): https://medium.com/@prajacta.khopkar/d9704909baf

**Comment by Trott** [comment]
Code formatting is still 👎 on that Packt article. No indentation, etc.

**Comment by WaleedAshraf** [comment]
👎 for Packt article code formatting.

**Comment by ZibbyKeaton** [comment]
How about now with the formatting: https://medium.com/@Packt_Pub/image-manipulations-using-express-7398a6fa1491

**Comment by Trott** [comment]
Formatting is still missing indentation which is a total deal-breaker IMO. Makes the code very difficult to read. 

```js
let image = sharp({
create : {
width : width,
height : height,
channels : 4,
background : { r: 0, g: 0, b: 0 },
}
});
```

**Comment by WaleedAshraf** [comment]
Should be like this.
```js
let image = sharp({
  create: {
    width: width,
    height: height,
    channels: 4,
    background: { r: 0, g: 0, b: 0 },
  }
});
```

And all the gist are `.txt` files. It should be `.js`

**Comment by ZibbyKeaton** [comment]
@WaleedAshraf can I connect you directly to the author to help them solve this issue. I think that will likely be easier here.

**Comment by WaleedAshraf** [comment]
@ZibbyKeaton yes. Sure.

**Comment by WaleedAshraf** [comment]
@Trott can you take a final look at: https://medium.com/@Packt_Pub/image-manipulations-using-express-7398a6fa1491

Author has fixed the formatting. 👍 from my side.

**Comment by Trott** [comment]
Formatting looks fine. I haven't read it yet so I have no comment on the content (yet?).

**Comment by WaleedAshraf** [comment]
@Trott any update on this?

**Comment by Trott** [comment]
> @Trott any update on this?

Was hoping others would take a look, to be honest. Image manipulation is not my area of expertise and I'm not using Express much these days either. I mean, it seems OK to me I guess, but I'd hope someone else more interested and/or experienced would take a look.

**Comment by WaleedAshraf** [comment]
@ZibbyKeaton can we tag someone else for review?
@nodejs/nodejs-collection

**Comment by WaleedAshraf** [comment]
Closing this issue as the date has passed for the blog post. Thanks everyone.
