### ISSUE TITLE
Submissions for Week of 8.14.18

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#30]
Ben Coe has been working with several folks at Google and on the Node.js project over the past year to add code coverage functionality to the project. He just finished writing a draft telling the story of this experience: https://gist.github.com/bcoe/e0a92ac00c67f6f61ae83ae49333ea49

I think this is a good fit for the Node.js Collection. If you agree, please confirm with a 👍 if you disagree please add 👍If you have questions or suggestions, please leave a comment below.

**Comment by Trott** [comment]
Gave it a very quick look (because: weekend), but the topic is 👍 and nothing jumped out at me as problematic.

**Comment by mhdawson** [comment]
Asked a few questions on the article.  Would like us to position versus make coverage so that we don't have confusion as to when we'd recommend one versus the other.

**Comment by WaleedAshraf** [comment]
Nice 👍 
It's nice to have a built-in coverage tool. It'd be better if we can clearly mention that it's in a very early stage right now. Expect bugs and missing features. (not production ready yet)
