### ISSUE TITLE
Node.js Collection Suggested Updates and Changes

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#31]
**As the Node.js Collection grows, I've noticed a few challenges arising:**
- There is no current process for onboarding editors
- There is no set standard for reviewing content - this has slowed down the process of getting items reviewed and submitted
- We are not fully utilizing the automation features of Medium 

**Given this, I would recommend the following:** 
- A more formalize submission process that utilizes Medium
- Onboarding and review process for Node.js Collection editors 

Below are the areas that I would recommend we update to ensure the process is more fluid. If you have written for the Node.js Collection or are an editor, I would greatly appreciate your feedback and thoughts on this.

**WRITERS GUIDELINES UPDATED**
*This is an update to a few sections found in “[Introducing the Node.js Collection](https://medium.com/the-node-js-collection/introducing-the-node-js-collection-4d0d60e72a64)” and the About Node.js Collection on GitHub. Suggested adjustments with the newly proposed process:

_“How To Submit for Consideration”_
- Please submit a brief summary and the topic of the post to medium@nodejs.org for consideration.
- Members of the Node.js Collection Editorial Team and Node.js Foundation PR team will review your submission in a timely manner and provide the green light to draft the entire article or provide feedback of direction. Please allow at least one week for this process.
- You will be added as a writer to the Node.js Collection; once your blog post is finalized, please submit the full article as a DRAFT and alert the editors via medium@nodejs.org.
- You will be assigned an editor (see review process for original posts below)
- Once your submission has been approved, it will be added to the Node.js Foundation Medium publication - a publish date will be provided, so you may plan to promote accordingly through your personal and company’s social media channels.

_“Review Process for Original Posts”_
- The review team will provide comments and edits.
- The writer will be alerted of these edits and suggestions; the author of the post has the final sign off on content and can approve/accept all edits. 
- If the author feels comfortable, the post should come with a list of those who helped edit the content. 
- The review process could take up to a month depending on the number of edits and revisions involved.
- The review process and edits need will happen on Medium with few exceptions. 

_“Handy Tools for Writing Posts on Medium/Best Practices”_
- If this article is on another Medium publication, you cannot submit it on the Node.js Collection Medium publication - Medium does not allow the same article on multiple publications. 
- This post is a good guide on what you should think about as a writer on Medium 
If you want to convert Markdown to Medium, we suggest this handy tool: http://markdowntomedium.com/
- And another helpful tool, this converts Google Docs to Markdown, which is incredibly useful for those of us who actually use the Google Docs formatting: https://github.com/mangini/gdocs2md/blob/master/converttomarkdown.gapps
- If you use any code examples in your post, please post them through GitHub Gist and embed them in your post.

**EDITOR PROCESS STORED ON GITHUB**
_*This would be completely new content that we can store on GitHub and share with those who are interested in becoming editors of the Node.js Collection._ 

**ABOUT**
Node.js Collection is a publication on Medium that focuses on content for Node.js users. The content can be for those who are just getting started with Node.js to those who are more advanced. You can learn more about the publication via this introduction blog.

The Node.js Collection receives a lot of abstracts per month and relies on technical editors to help ensure quality control in what is produced on the channel. Technical editors provide the following:
- Approve suggested abstracts that are submitted to medium@nodejs.org.
- Review and edit content drafts submitted to the Node.js Collection Medium page.

**BECOME AN EDITOR**
- Submit your interest to the current Node.js Collection editors via medium@nodejs.org. Provide your area of expertise.
- Once you are accepted, you will be added as an editor to Node.js Collection (Medium account is required). You will also be added to the alias medium@nodejs.org.

**REVIEW PROCESS**
- Writers submit an abstract via email at medium@nodejs.org. Editors have one week to provide approval - this is done internally on the alias and not to be shared with the writer until a final decision and suggested changes are reached as a group. 
- If the article is approved, the writer will submit a draft on Medium and an editor or two will be assigned to review - we suggest providing feedback to the writer two to three weeks once it is submitted depending on the number of changes and recommendations.
- The writer to approve all content and send a note to medium@nodejs.org once finished.
- Editor/a member of the Node.js Foundation PR team to review one final time and accept into publication.

**Comment by WaleedAshraf** [comment]
@ZibbyKeaton this is great and much needed. I'm not sure who but we should ping more folks here. We need more people in the review process.

**Comment by ZibbyKeaton** [comment]
Tagging @bnb @Trott as they have been editors/writers in the past. Wondering if y'all had any thoughts on the suggested changes that I've proposed?

**Comment by amiller-gh** [comment]
@nodejs/community-committee – friendly reminder to email medium@nodejs.org if you're interested in helping edit incoming articles as discussed in todays meeting!

Rachel will help codify these changes and get the new process into gear.

**Comment by RRomoff** [comment]
Thanks Adam. Happy to have joined the Comm comm and to be working with you all. If there's any additional feedback to what Zibby already outlined, please let me know and we can chat through during the next meeting. I'm also doing some best practices research to see how else we can best utilize medium. Happy to share what I find out and see how we can incorporate.

**Comment by WaleedAshraf** [comment]
We have simplified the process as per this issue: https://github.com/nodejs/community-committee/issues/608
I'll close this issue. Feel free to re-open if needed.
