### ISSUE TITLE
Blogs Week of October 28, 2018

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#32]
I've been a bit behind with Node.js Collection items... But I have a few that are looking pretty good. 

- [ApostropheCMS 3.0](https://medium.com/@apostrophecms/7a5685db1f0a): the work begins! This is the second piece of content we've received from the group, they also provided us details in how they created ApostropheCMS 2.0 too. I think it's informative and well written. Please give this a 👍by next Wednesday, November 7 if you agree with this going into NC.

- [Deploying a Stateful Application on Google Cloud Kubernetes Engine](https://blog.risingstack.com/deploying-a-stateful-application-on-google-cloud-kubernetes-engine/): Please give this a 🎉 by next Wednesday, November 7 if you agree with it going into NC.

If you disagree with any of this content, please write a comment with feedback to why you don't think this should go in. 

Thanks!

**Comment by WaleedAshraf** [comment]
Closing this issue as the date for blog post has passed. Thanks.
