### ISSUE TITLE
Node.js Speakers Bureau 

### ISSUE THREAD

**Issue by codeekage** [nodejs/nodejs-collection#33]
Hey 👋, can they be a blog post to engage the public on Node.js Speaker Bureau Programme? 

I'd also suggest preparing slides, and short briefs around nodejs related topics and activities for speakers that can be easily submitted to event organiser.

This brings some sort of uniformity in the nodejs projects and nodejs attended events around the global. Giving the community one voice, and speaking the same language at different events and locations. 

This does not restrict speakers from preparing personal slides; but improves the community by spreading information(s) the node community should be aware of.

**Comment by WaleedAshraf** [comment]
@codeekage If you have something to publish, feel free to submit it for review. We can also discuss this in the next CommComm meeting if you want.

**Comment by WaleedAshraf** [comment]
I'll close this issue as there's no progress. Feel free to reopen if needed.
