### ISSUE TITLE
Interested in becoming a technical editor

### ISSUE THREAD

**Issue by Emuentes** [nodejs/nodejs-collection#35]

**Comment by WaleedAshraf** [comment]
Hi @Emuentes, sorry for the delayed response.
If you are still interested, I can add you to the medium editor's email list.

**Comment by Emuentes** [comment]
@WaleedAshraf sure, I think I will enjoy helping out. Happy to contribute.

**Comment by WaleedAshraf** [comment]
Hi @Emuentes. Really sorry for the late response, second time.
The [nodejs/community-committee](https://github.com/nodejs/community-committee) got retired and this initiative also. Though, we still have kept Node.js Collection Medium page, for occasional posts and announcements. Are you still interested?

**Comment by Emuentes** [comment]
@WaleedAshraf I don't know that I will have as much bandwidth for this as the younger me did 😂

If you want to chat via zoom/slack -- or something a little easier to connect over than GitHub repo comments -- I'm interested in understanding what is actually still needing to be done.

Find me in the NodeJS slack workgroup if you would like to discuss.

Thanks for the reply, no worries about the delay, I understand.

Have an excellent weekend,
-Edgar

**Comment by WaleedAshraf** [comment]
Discussed with @Emuentes that it doesn't make sense to add more reviewers now as the initiative is not active anymore. I'll close this issue.
