### ISSUE TITLE
Access of medium account and email.

### ISSUE THREAD

**Issue by WaleedAshraf** [nodejs/nodejs-collection#39]
While working on the new process for blog submission, I have a few questions.

- Who has access to medium@nodejs.org email?
- Who is on the list to get emails sent to this id?
- Who has access to the Node.js Collection Medium account?
- Who is on the editor list?
- What are other roles on the Medium account?

Also,
I want to get access to both the email address and the Medium account so that I can have a better look and can suggest changes where needed.

cc @nodejs/community-committee @RRomoff

**Comment by ahmadawais** [comment]
I'd also like to help improve and understand the process of new blog post
submission. 👋


-- 


AHMAD AWAIS <https://twitter.com/MrAhmadAwais/>
❯ Open Source & JavaScript Dev Advocate ❯ Node.js Foundation Community
Committee Member
❯ Google Developers Expert for Web Tech ❯ WordPress Core Developer ❯ EE-CS
Engineer
❯ Hilarious comedian ❯ Self-confessed technology addict. ;)

*→ Read my blog: AhmadAwais.com <https://ahmadawais.com/> *
*→ *

*Twitter <https://twitter.com/MrAhmadAwais/> | GitHub
<https://github.com/AhmadAwais> | Facebook
<https://www.facebook.com/ahmadawais> | LinkedIn
<https://www.linkedin.com/in/MrAhmadAwais/> → Skype/Slack &
More: MrAhmadAwais → I've released a course on VSCode.pro
<https://vscode.pro/?utm_source=EmailFooter>  *

**Comment by WaleedAshraf** [comment]
I got the access to Medium account to manage it. Good for now. I'll close this issue.
@ahmadawais You may already know, we have [simplified the process](https://github.com/nodejs/nodejs-collection/pull/41). Limited to collaborators and contributors, though anyone can get in touch through the email. If you have more questions, feel free to reach out to me.
