### ISSUE TITLE
Node.js localization

### ISSUE THREAD

**Issue by WaleedAshraf** [nodejs/nodejs-collection#42]
We have received a submission for this article. Would be nice if people can review it.

https://docs.google.com/document/d/1SkBjFe9zLxKIRRhGhU5VcUFSSB6cYNkfh9AhBpl4gnc/edit

cc @alexandrtovmach @JohnTitor @mcollina @bnb

**Comment by bnb** [comment]
IMO we should not be publishing to the collection anymore.

**Comment by WaleedAshraf** [comment]
@bnb Should I update the readme that it's limited to Node.js collaborators and working groups?

**Comment by WaleedAshraf** [comment]
The last post was on 10th Jan. I'm not sure who posted/approved it.
https://medium.com/the-node-js-collection/help-wanted-node-addon-apis-road-to-full-unit-test-coverage-1d3dbef8f7ab
