### ISSUE TITLE
Cleanup nodejs-collection and accounts related to it.

### ISSUE THREAD

**Issue by WaleedAshraf** [nodejs/nodejs-collection#44]
Node.js Collection initiative was kind of left out when we retired CommComm, and we didn't make any final/concrete decision on it.

These are the accounts we have on Medium

- Node.js Collection Publication: https://medium.com/the-node-js-collection
- Node.js user account: https://nodejs.medium.com/
- Email: medium@nodejs.org (I'm on this alias, not sure who/how many more people we have)
- 18 people have **Editor** access to Node.js Collection Publication
- 39 people have **Writer** access to Node.js Collection Publication

I suggest that we completely remove this initiative. Deactivate both accounts and the Email alias. This way there will no maintenance will be required from anyone.

cc @joesepi @bnb

**Comment by BethGriggs** [comment]
I'm not familiar with the Medium user deactivation consequences - will articles such as [Undici 4](https://nodejs.medium.com/introducing-undici-4-1e321243e007) and [Node.js 16 Release Announcement](https://medium.com/the-node-js-collection/node-js-16-available-now-7f5099a97e70) continue to be available if you deactivate both accounts?

**Comment by WaleedAshraf** [comment]
Yes, deleting or deactivating any of the accounts will remove its content.
Deactivating will delist the content, and Deleting an account will permanently delete all content.

**Comment by sxa** [comment]
Having been on the receiving end of losing blogs elsewhere and the associated broken links in the internet to them I'd generally be against removing content that might still be useful to people.

What is the maintenance burden required to keep it active? (i.e. what would we be saving by removing the content)

**Comment by mhdawson** [comment]
I agree we don't want to delete existing blogs.

**Comment by Trott** [comment]
Yeah, I don't think we want to delete content if we can avoid it. We just want to make it clear that we're not adding new content. I mean, ideally speaking. I haven't looked at practical issues, so @WaleedAshraf would know about issues I'm failing to consider.

**Comment by WaleedAshraf** [comment]
It's a valid point to keep the existing content. We can keep the accounts as is, but there's still some cleanup that should be done. Those medium accounts have thousands of followers, and I don't want someone from (~50) editors/writers to accidentally post something which violates COC, etc. The other concern is that "[medium@nodejs.org](mailto:medium@nodejs.org)" keeps getting submissions or spam emails. I'll be fine if we completely remove this alias, or at least clear up the forwarding list to limited people. The credentials of these medium accounts have to be managed by someone. Currently only @bnb has the credentials.
If we are [moving twitter account](https://github.com/nodejs/admin/issues/686#issue-1230304818) to OpenJS Foundation than medium accounts should also be part of that transfer.


- Update the readme ([something like this pull/43](https://github.com/nodejs/nodejs-collection/pull/43))
- Archive this repo and remove the team once the readme is updated.
- Remove all the editors and writers from the medium accounts. (keep only limited people)
- Transfer the management of accounts to OpenJS Foundation OR move it under [Social Team](https://github.com/nodejs/social-team) (if we are going to keep that team).

**Comment by mhdawson** [comment]
@WaleedAshraf what you suggest here makes sense. Reducing the set of people who might post to the account makes sense.  

Is the alias tied to the login for the medium account ?  If not then just getting rid of it makes sense to me.   In terms of the login itself I think reducing access to the same set of people who can access the twitter account makes sense to me.

**Comment by WaleedAshraf** [comment]
The email medium@nodejs.org is being used in the contact info section of the Node.js Collection page.

I have cleaned up the writers, but can't remove editors. I think only @bnb has permission for that.
This is the current list,

![image](https://user-images.githubusercontent.com/8335457/168690096-8cdd1faf-87a9-41dc-826e-e00f13d7f987.png)

**Comment by mhdawson** [comment]
@bnb is the nodejs editor an account that might become a user with the rights to add/remove editors and if so would it make sense to do that and then store the password somewhere accessible to the TSC ?

**Comment by bnb** [comment]
@mhdawson it's not an account, but a role AFAIK. I think the Foundation *does* own an account, which we could set as the only Editor and provide that as the TSC account if they're willing to give it to us (and I hope they would given we're just going to be archiving it. It there's buttons I need to press, happy to do so whenever :)

**Comment by mhdawson** [comment]
@bnb setting the foundation account as the only editor and then sharing with the TSC sounds like the right way to go. 

@rginn, @jorydotcom do one of you have the account/credentials for the account @bnb mentions above?

**Comment by Trott** [comment]
Let's create a checklist of things that need to happen before this can be closed. Please edit this comment and add things.

- [x] Edit https://medium.com/the-node-js-collection/about to say that the Node.js Collection no longer publishes or accepts contributions, and also to remove mention of medium@nodejs.org. 
- [x] Delist/unpublish/hide https://medium.com/the-node-js-collection/introducing-the-node-js-collection-4d0d60e72a64 and/or remove mention of medium@nodejs.org in that post along with adding a note at the top saying that the initiative has been...whatever the right word/phrase is...decommissioned? wound down?
- [x] Optional, but maybe post one last item to Node.js Collection saying the Node.js Collection isn't something we're doing anymore, there's lots of great content elsewhere, thanks for your interest, etc.
- [x] Update the README (#43)
- [x] Archive this repo
- [x] Remove the nodejs-collection GitHub team
- [x] Remove all writers/editors from the Medium account except for maybe one or two Foundation and/or TSC folks
  - [x] writers removed
  - [x] editors removed

Please edit freely, add things I'm missing, etc. (And, of course, mark things done as they get done!) Thanks.

**Comment by Trott** [comment]
If someone wants to temporarily or permanently grant me owner/editor/whatever role in the Medium account, I'm happy to do most of the cleanup. I don't have the right permissions right now, though.

**Comment by bnb** [comment]
Did the first two 👍🏻

**Comment by WaleedAshraf** [comment]
Removing the editors can only be done from the owner's account. @bnb your account has that access. no?

**Comment by bnb** [comment]
I don't believe so, no. I can remove writers but not editors (I would upload a screenshot but lol tethering while sitting on a plane waiting for maintenance). I'm assuming the Foundation "Node.js" account is the one that can indeed do this.

**Comment by Trott** [comment]
@rginn Do you know if someone at the Foundation has administrative access to the Node.js Collection Medium thing that we're trying to decommission?

**Comment by rginn** [comment]
I'm doing an archeological dig through our Node.js Foundation files and staff. I'll report back after I find out.
