### ISSUE TITLE
Add CONTRIBUTING.MD

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/nodejs-collection#5]
I saw a good point brought up in another PR that we don't have the process for submitting a PR and getting it approved. I'd be happy to file this unless someone else is already working on it.

**Comment by bnb** [comment]
I don't believe someone else is working on it already. I can also file, if needed 😄

**Comment by WaleedAshraf** [comment]
I don't think we need this now. Closing this issue. Feel free to open again, if needed.
