### ISSUE TITLE
A couple more suggestions

### ISSUE THREAD

**Issue by mhdawson** [nodejs/nodejs-collection#6]
https://developer.ibm.com/node/2017/07/05/node-js-errors-changes-you-need-to-know-about/

https://developer.ibm.com/node/2017/07/05/node_options-landed-8-x/

**Comment by ZibbyKeaton** [comment]
Sorry for the delay here:

We had one question for @sam-github; see here https://docs.google.com/a/linuxfoundation.org/document/d/1HDP2AgXmOeHtEIohsppxFD5C7BY5m2TCX1Z4qHznT3Y/edit?usp=sharing. Also, Sam do you have your own Medium page? If not, then would you mind if we posted this on the Node.js Foundation Medium page? We would link back to this original post and then also include your bio (please send over two to three sentences about yourself). Simeon Vincent did the technical review of this and we would like to include a thank you to him at the end of the post. Are you okay with this?

@mhdawson we had a few questions and suggested expansions to your post. Please view it here: https://docs.google.com/document/d/1juNe2rDla8UUatYri7hKStA6-Pz_XfMhkMoFb5ub9c8/edit?ts=5973c687#heading=h.mbftwp4ouiy. 

Also, similar to my questions for Sam:
- Do you have a Medium page?
- If not, are you okay with us adding this to the Node.js Foundation Medium page? We would need a short bio from you, if we post via the Node.js Foundation Medium page.
- Are you okay with us including a thank you and recognition to Simeon regarding his edits and suggestions to this post?

Thank you both!

**Comment by mhdawson** [comment]
These both are done closing.
