### ISSUE TITLE
Node.js Collection Blogs to Edit

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/nodejs-collection#7]
@svincent We have a lot of blogs in the hopper. I think some will take a lot less time than others. I've created a special editorial calendar (below) to prioritize reviews based on ease and date sent. I have one highlighted in red. Please do not review this one as we need to provide major feedback to the author.

Please leave only suggested edits to these documents and comments, so the author can review all our changes. 
Editorial Calendar here: 
https://docs.google.com/spreadsheets/d/1xT8KEolYqcKj2L4Dijx8dbvwqKsOL_2uCADhK_xzOx8/edit#gid=0

**Comment by ZibbyKeaton** [comment]
@Trott I saw that you requested access to this document. Are you interested in being a technical editor? If so, then I will divide the blog list between you and @svincent.

**Comment by Trott** [comment]
@ZibbyKeaton Sorry, I mistook this for a generic call for reviews. You can ignore me. (Especially this week/weekend. Traveling and not sure how much internet access I'll have.)

**Comment by dotproto** [comment]
Thanks, @ZibbyKeaton! I'll make some time to do at least one article tonight.

**Comment by dotproto** [comment]
@ZibbyKeaton, sorry for the delay. I just reviewed Guilherme Oenning's article and made a few minor tweaks (e.g. url -> URL). Unfortunately, I think I did it wrong; I assumed Google Docs would auto-add comments for my changes, but it did not.

The article's terminology, API use, and code samples all look good. It might be worth considering using gitch.com to make code samples easily runnable. I took the liberty of throwing together an example: https://glitch.com/edit/#!/indigo-soprano

**Comment by ZibbyKeaton** [comment]
Awesome and thank you - I can easily see your changes when I look at the previous draft @svincent.

**Comment by dotproto** [comment]
@ZibbyKeaton I'm at Comic Con, but I'm taking today from the festivities to get some side project work done. I'm going to take a look at "Having Your Node.js Cake and Eating It Too" since it's next in the list, but I'm hoping I can get a couple reviewed over the next few hours.

Also, a procedural note. I think I the right way to do edits on Google Docs -- we'll see soon though.

**Comment by ZibbyKeaton** [comment]
@svincent you rock! Hope you had a good time at Comic Con. I saw you got through a few of these posts. I'll take a look at them and let the authors know of your edits.
