### ISSUE TITLE
Tooling to Convert Markdown to Medium posts

### ISSUE THREAD

**Issue by bnb** [nodejs/nodejs-collection#8]
Wanted to share this, found in a blog post originally shared by @mikeal in https://github.com/nodejs/evangelism/issues/218, that may be a helpful tool for the Node.js Collection. 

http://markdowntomedium.com/

This tool also raises the topic of tooling this Team uses. In combination with this, I've got a Google Script to convert Google Docs to Markdown - which could be a nice solution for us to have coverage for converting from basically any input method. Would definitely appreciate feedback/thoughts 🙏

**Comment by WaleedAshraf** [comment]
I don't think we will need this anytime soon. Closing this issue. Feel free to re-open if needed.
